### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DrearyWillow** [DrearyWillow/pdsls-redirector#1]
- [x] support pinksea replies https://pinksea.art/did:plc:y33bag2x6rndakrseukqrtf3/oekaki/3lcfr7x37ckcj#did:plc:y33bag2x6rndakrseukqrtf3-3ldidgfrgak67
- [x] ouranos support alternative lexicons
- [x] support bookhive https://bookhive.buzz/profile/c0dk3lpm3.bsky.social
- [x] support recipe.exchange https://bsky.app/profile/recipe.exchange/post/3ld2u47y23c2n
- [x] feat: copy at-uri button, or copy did link button
- [ ] feat: resolve sites to arbitrary sites
- [x] change rkey regex to be more appropriate: (?<rkey>[A-Za-z0-9._~:-]{1,512}) https://atproto.com/specs/record-key

**Comment by DrearyWillow** [comment]
most of these have been complete for a while and this is a dumb way to keep track of TODOs so i'm closing
